paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_characters:
    path: src/content/docs/characters
    icon: docs_add_on
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_factions:
    path: src/content/docs/factions
    icon: celebration
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_locations:
    path: src/content/docs/locations
    icon: dataset
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_lore:
    path: src/content/docs/lore
    icon: auto_stories
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_quests:
    path: src/content/docs/quests
    icon: assignment
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_items:
    path: src/content/docs/items
    icon: inventory_2
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_magic:
    path: src/content/docs/magic
    icon: auto_awesome
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_creatures:
    path: src/content/docs/creatures
    icon: pets
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_campaign_log:
    path: src/content/docs/campaign-log
    icon: history
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_about:
    path: src/pages/about
    icon: all_out
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_archives:
    path: src/pages/archives
    icon: archive
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_docs:
    path: src/pages/docs
    icon: bike_dock
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_links:
    path: src/pages/links
    icon: page_info
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_projects:
    path: src/pages/projects
    icon: nest_protect
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_search:
    path: src/pages/search
    icon: image_search
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_tags:
    path: src/pages/tags
    icon: car_tag
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_terms:
    path: src/pages/terms
    icon: pageless
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
