paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_characters:
    path: src/content/docs/characters
    name: Characters
    icon: person
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_factions:
    path: src/content/docs/factions
    name: Factions
    icon: groups
    disable_url: false
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: /.cloudcannon/schemas/faction.mdx
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon:
        preview:
        _editables:
        _enabled_editors:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
  docs_locations:
    path: src/content/docs/locations
    name: Locations
    icon: mountain_flag
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_lore:
    path: src/content/docs/lore
    name: Lore
    icon: auto_stories
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_quests:
    path: src/content/docs/quests
    name: Quests
    icon: exclamation
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_items:
    path: src/content/docs/items
    name: Items
    icon: swords
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_magic:
    path: src/content/docs/magic
    name: Magic
    icon: auto_awesome
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_creatures:
    path: src/content/docs/creatures
    name: Creatures
    icon: pets
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_campaign_log:
    path: src/content/docs/campaign-log
    name: Campaign Log
    icon: history
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  $.tags:
    type: multiselect
    options:
      allow_empty: true
      values: _select_data.tags[?(@.type == 'docs')].name
      required: true
    cascade: true
  $.faction_campaign_log:
    type: multiselect
    options:
      allow_empty: true
      values: collections.docs_campaign_log.title
    cascade: true
  $.faction_location:
    type: multiselect
    options:
      allow_empty: true
      values: collections.docs_locations.title
    cascade: true
  $.faction_related:
    type: multiselect
    options:
      allow_empty: true
      values: collections.docs_factions.title
    cascade: true
  $.faction_status:
    type: select
    options:
      allow_empty: true
      values: _select_data.faction_status
      required: true
    cascade: true
  $.faction_type:
    type: multiselect
    options:
      allow_empty: true
      values: _select_data.faction_type
      required: true
    cascade: true
_select_data:
  tags:
    - name: Mercenary
      type: docs
    - name: Worldbuilding
      type: blog
  faction_status:
    - Active
    - Inactive
    - Dead
    - Unknown
  faction_type:
    - Adventuring
    - Community
    - Economic
    - Ethnicity
    - Magical
    - Military
    - Political
    - Religious
    - Technological
_editables:
  content:
    blockquote: true
    bold: true
    format: p h2 h3 h4
    italic: true
    link: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    bulletedlist: true
    numberedlist: true
    indent: true
    outdent: true
    join_above: true
    join_below: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
commit_templates:
  - template_string: '{message}'
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
