paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_characters:
    path: src/content/docs/characters
    name: Characters
    icon: person
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_factions:
    path: src/content/docs/factions
    name: Factions
    icon: groups
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_locations:
    path: src/content/docs/locations
    name: Locations
    icon: mountain_flag
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_lore:
    path: src/content/docs/lore
    name: Lore
    icon: auto_stories
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_quests:
    path: src/content/docs/quests
    name: Quests
    icon: exclamation
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_items:
    path: src/content/docs/items
    name: Items
    icon: swords
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_magic:
    path: src/content/docs/magic
    name: Magic
    icon: auto_awesome
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_creatures:
    path: src/content/docs/creatures
    name: Creatures
    icon: pets
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  docs_campaign_log:
    path: src/content/docs/campaign-log
    name: Campaign Log
    icon: history
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
commit_templates:
  - template_string: '{message}'
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
